// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
// Lazy-import supabase only when the publishable key is present to avoid
// throwing during builds or in environments where Supabase isn't configured.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    try {
      const VITE_KEY = import.meta.env?.['VITE_SUPABASE_PUBLISHABLE_KEY'];
      if (!VITE_KEY) return next({ headers: {} });
      const { supabase } = await import('./client');
      const { data } = await supabase.auth.getSession();
      const token = data.session?.access_token;
      return next({ headers: token ? { Authorization: `Bearer ${token}` } : {} });
    } catch {
      return next({ headers: {} });
    }
  },
)
